substitutions:
  # Set rotation: "0", "90", "180", or "270"
  display_rotation: "180"

esphome:
  name: waveshare-p4-box
  friendly_name: WaveShare P4 Box

packages:
  base: !include common/base_config.yaml
  hardware: !include common/hardware_io.yaml
  logic: !include common/logic_globals.yaml
  sensors: !include common/sensors_ha.yaml
  controls: !include common/controls.yaml
  ui: !include common/display_lvgl.yaml
