/**
 * @file audio_alert.c
 * @brief Spoken alert playback over the onboard ES8311 speaker (thread-safe).
 *
 * Architecture: audio_alert_speak() turns (type, instance, value) into a list
 * of clip ids and posts it to a queue.  The audio_alert task drains the queue,
 * lazily brings up the speaker codec on first use, plays each sentence clip by
 * clip and closes the codec once the queue stays empty for DRAIN_WAIT_MS
 * (closing puts the power amp in standby, which kills the idle hiss).
 *
 * Clips are headerless 16 kHz / 16-bit / mono PCM embedded via EMBED_FILES in
 * main/CMakeLists.txt.  Placeholders are generated by
 * tools/gen_placeholder_clips.py; dropping real renders in main/audio_clips/
 * needs no code change.
 */

#include "audio_alert.h"
#include "app_config.h"
#include "bsp/esp-bsp.h"        /* bsp_audio_codec_speaker_init */
#include "esp_codec_dev.h"
#include "esp_heap_caps.h"
#include "esp_log.h"
#include "esp_timer.h"
#include "freertos/FreeRTOS.h"
#include "freertos/queue.h"
#include "freertos/task.h"
#include <stdatomic.h>
#include <string.h>

static const char *TAG = "audio_alert";

#define CLIP_SAMPLE_RATE    16000
#define SENTENCE_MAX_CLIPS  16      /* worst case: disconnect group =
                                     * chime+warning+instance+10 equipment
                                     * +"and"+last equipment+disconnected = 16 */
#define SENTENCE_QUEUE_LEN  8   /* match the 8-deep flash queue in nina_alerts.c */
#define PCM_CHUNK_BYTES     2048
#define DRAIN_WAIT_MS       400     /* keep the PA up this long between sentences */
#define VALUE_MAX_TENTHS    9999    /* clamp: nothing above "999.9" is spoken */

/* ── Embedded clip registry ─────────────────────────────────────────────────
 * One list drives the extern declarations, the id enum, the address table and
 * the name table, so they cannot drift out of order.  EMBED_FILES derives the
 * symbol from the file's basename only, so the audio_clips/ subdirectory does
 * not appear in the symbol name.  Each X() argument is both the .pcm basename
 * and the name the /api/test/clip endpoint accepts.
 * The per-event phrase clips (voice_event_t) are appended at the END so every
 * existing CLIP_ID_* keeps its numeric value: SPIFFS overrides key by name,
 * but /api/test/clip and the Voice Clips UI index by id. */
#define CLIP_LIST(X)                                            \
    X(chime) X(warning)                                         \
    X(instance_1) X(instance_2) X(instance_3)                   \
    X(rms) X(hfr) X(above_limit) X(unsafe) X(point)             \
    X(digit_0) X(digit_1) X(digit_2) X(digit_3) X(digit_4)      \
    X(digit_5) X(digit_6) X(digit_7) X(digit_8) X(digit_9)      \
    X(connected) X(disconnected)                                \
    X(camera) X(mount) X(guider) X(focuser) X(filterwheel)      \
    X(rotator) X(safety) X(dome) X(flat) X(switch) X(weather)   \
    X(sequence_event) X(focuser_event) X(mount_event)           \
    X(meridian_flip) X(guider_event) X(safety_event)            \
    X(error_event) X(profile_changed) X(dome_event) X(flat_event)  \
    X(boot_jingle) X(rms_above) X(hfr_above) X(and)                 \
    X(sequence_started) X(sequence_finished) X(sequence_step_failed)  \
    X(autofocus_complete) X(autofocus_failed)                        \
    X(meridian_flip_starting) X(mount_parked)                        \
    X(conditions_safe) X(guiding_stopped)                            \
    X(dome_shutter_closed) X(dome_shutter_opened)                    \
    X(platesolve_failed) X(camera_timeout)

#define CLIP_EXTERN(name)                               \
    extern const uint8_t _binary_##name##_pcm_start[];  \
    extern const uint8_t _binary_##name##_pcm_end[];
#define CLIP_ENUM(name)  CLIP_ID_##name,
#define CLIP_ENTRY(name) { _binary_##name##_pcm_start, _binary_##name##_pcm_end },
#define CLIP_NAME(name)  #name,

CLIP_LIST(CLIP_EXTERN)

/* CLIP_ID_instance_1 and CLIP_ID_digit_0 are indexed with an offset. */
typedef enum {
    CLIP_LIST(CLIP_ENUM)
    CLIP_COUNT
} clip_id_t;

typedef struct {
    const uint8_t *start;
    const uint8_t *end;
} clip_t;

static const clip_t      s_clips[CLIP_COUNT]      = { CLIP_LIST(CLIP_ENTRY) };
static const char *const s_clip_names[CLIP_COUNT] = { CLIP_LIST(CLIP_NAME) };

/* ── Module state ───────────────────────────────────────────────────────── */
typedef struct {
    uint8_t clip[SENTENCE_MAX_CLIPS];
    uint8_t count;
} sentence_t;

static QueueHandle_t          s_queue = NULL;
static QueueHandle_t          s_free_q = NULL;  /* retired override buffers, freed
                                                 * by the playback task between
                                                 * sentences (never mid-clip) */
static esp_codec_dev_handle_t s_codec = NULL;   /* task-owned, lazily created */
static bool                   s_codec_dead = false;   /* init failed once: never retry
                                                       * (BSP leaves dangling I2S handles
                                                       * that assert on a second attempt) */
static uint8_t                s_pcm_buf[PCM_CHUNK_BYTES];

/* ── Clip overrides (voice_store.c) ─────────────────────────────────────────
 * Per-clip custom PCM in PSRAM that replaces the embedded clip at playback.
 * Lock-free single-writer publication via C11 atomics: the P4 is dual-core
 * RVWMO, so plain/volatile stores may reorder between cores and an explicit
 * acquire/release pairing is required.  Writer ordering
 * (audio_alert_set_override, serialized by voice_store's mutex):
 *   apply: store len (relaxed) first, then buf with release — the release
 *          store publishes len, so a reader whose acquire load sees the new
 *          buf also sees its len;
 *   clear: store buf NULL (relaxed) first, then len 0 (relaxed) — a reader
 *          that sees a non-NULL buf never pairs it with a cleared len.
 * The reader (play_clip, playback task only) loads buf with acquire, then
 * len relaxed. */
typedef struct {
    _Atomic(const uint8_t *) buf;
    _Atomic size_t           len;
} clip_override_t;

static clip_override_t s_override[CLIP_COUNT];

/* ── Sentence assembly ──────────────────────────────────────────────────── */
static void push_clip(sentence_t *s, clip_id_t id) {
    if (s->count < SENTENCE_MAX_CLIPS) {
        s->clip[s->count++] = (uint8_t)id;
    }
}

/* Speak `value` as "<digits> point <digit>", e.g. 1.25 -> "one point three".
 * Integer math throughout: no float formatting on the caller's stack. */
static void push_value(sentence_t *s, float value) {
    int tenths = (value > 0.0f) ? (int)(value * 10.0f + 0.5f) : 0;
    if (tenths > VALUE_MAX_TENTHS) tenths = VALUE_MAX_TENTHS;

    int whole = tenths / 10;
    if (whole >= 100) push_clip(s, CLIP_ID_digit_0 + (whole / 100) % 10);
    if (whole >= 10)  push_clip(s, CLIP_ID_digit_0 + (whole / 10) % 10);
    push_clip(s, CLIP_ID_digit_0 + whole % 10);
    push_clip(s, CLIP_ID_point);
    push_clip(s, CLIP_ID_digit_0 + tenths % 10);
}

/* Assemble the announcement.  Shared by the live, test-page and preview entry
 * points -- the only difference between them is the alert_voice_enabled gate --
 * so the alert_voice_brief mode applies to all of them automatically.
 * Brief mode drops the warning clip and, for RMS/HFR, replaces the spoken
 * value + "above limit" with a single "is above set threshold" clip.
 * Returns false for arguments that have nothing sensible to say. */
static bool build_sentence(sentence_t *s, alert_type_t type, int instance_idx,
                           float value) {
    if (instance_idx < 0 || instance_idx > 2) return false;

    bool brief = app_config_get()->alert_voice_brief != 0;

    memset(s, 0, sizeof(*s));
    push_clip(s, CLIP_ID_chime);
    if (!brief) push_clip(s, CLIP_ID_warning);
    push_clip(s, CLIP_ID_instance_1 + instance_idx);

    switch (type) {
    case ALERT_RMS:
    case ALERT_HFR:
        if (brief) {
            /* Single fused clip ("HFR is above set threshold."): metric and
             * predicate rendered as one utterance so no clip-gap pause splits
             * the phrase. */
            push_clip(s, (type == ALERT_RMS) ? CLIP_ID_rms_above : CLIP_ID_hfr_above);
        } else {
            push_clip(s, (type == ALERT_RMS) ? CLIP_ID_rms : CLIP_ID_hfr);
            push_value(s, value);
            push_clip(s, CLIP_ID_above_limit);
        }
        return true;
    case ALERT_SAFETY:
        push_clip(s, CLIP_ID_unsafe);
        return true;
    default:
        return false;   /* unknown type: nothing sensible to say */
    }
}

/* Equipment clip per equipment index.  Order MUST match equipment_type_t in
 * nina_websocket.c (EQ_CAMERA .. EQ_WEATHER). */
static const clip_id_t s_equipment_clip[] = {
    CLIP_ID_camera, CLIP_ID_mount, CLIP_ID_guider, CLIP_ID_focuser,
    CLIP_ID_filterwheel, CLIP_ID_rotator, CLIP_ID_safety, CLIP_ID_dome,
    CLIP_ID_flat, CLIP_ID_switch, CLIP_ID_weather,
};

/* Event clip per category, index = category_bit - 2 (categories 2..11). */
static const clip_id_t s_category_clip[] = {
    CLIP_ID_sequence_event, CLIP_ID_focuser_event, CLIP_ID_mount_event,
    CLIP_ID_meridian_flip, CLIP_ID_guider_event, CLIP_ID_safety_event,
    CLIP_ID_error_event, CLIP_ID_profile_changed, CLIP_ID_dome_event,
    CLIP_ID_flat_event,
};

/* Assemble an event announcement (shared by the live and the preview entry
 * points): chime + warning (bad-news categories only) + instance + either
 * "<equipment> connected/disconnected" (categories 0/1; bare
 * connected/disconnected when no equipment is given) or the category's event
 * clip (categories 2..11). */
static bool build_event_sentence(sentence_t *s, int category_bit,
                                 int instance_idx, int equipment_idx) {
    if (category_bit < 0 || category_bit > 11) return false;
    if (instance_idx < 0 || instance_idx > 2) return false;

    memset(s, 0, sizeof(*s));
    push_clip(s, CLIP_ID_chime);
    /* Warning tone only for the bad-news categories: equipment disconnects,
     * meridian flip, safety and error. */
    if (category_bit == 1 || category_bit == 5 ||
        category_bit == 7 || category_bit == 8) {
        push_clip(s, CLIP_ID_warning);
    }
    push_clip(s, CLIP_ID_instance_1 + instance_idx);

    if (category_bit <= 1) {
        if (equipment_idx >= 0 &&
            equipment_idx < (int)(sizeof(s_equipment_clip) / sizeof(s_equipment_clip[0]))) {
            push_clip(s, s_equipment_clip[equipment_idx]);
        }
        push_clip(s, (category_bit == 0) ? CLIP_ID_connected : CLIP_ID_disconnected);
    } else {
        push_clip(s, s_category_clip[category_bit - 2]);
    }
    return true;
}

/* Phrase clip per voice_event_t.  Order MUST match the enum in audio_alert.h.
 * 15 events, 13 new .pcm files: VOICE_EV_MERIDIAN_FLIP_COMPLETE reuses the
 * existing meridian_flip clip ("Meridian flip complete."), and
 * VOICE_EV_CONDITIONS_UNSAFE is reserved with no clip (see below). */
static const clip_id_t s_event_clip[VOICE_EV_COUNT] = {
    [VOICE_EV_SEQUENCE_STARTED]       = CLIP_ID_sequence_started,
    [VOICE_EV_SEQUENCE_FINISHED]      = CLIP_ID_sequence_finished,
    [VOICE_EV_SEQUENCE_STEP_FAILED]   = CLIP_ID_sequence_step_failed,
    [VOICE_EV_AUTOFOCUS_COMPLETE]     = CLIP_ID_autofocus_complete,
    [VOICE_EV_AUTOFOCUS_FAILED]       = CLIP_ID_autofocus_failed,
    [VOICE_EV_MERIDIAN_FLIP_STARTING] = CLIP_ID_meridian_flip_starting,
    [VOICE_EV_MERIDIAN_FLIP_COMPLETE] = CLIP_ID_meridian_flip,
    [VOICE_EV_MOUNT_PARKED]           = CLIP_ID_mount_parked,
    /* Reserved, no clip and no producer: the unsafe edge is announced by the
     * breach/alert engine's older `unsafe` clip ("Unsafe conditions."), so a
     * per-event phrase here would speak the same transition twice.  CLIP_COUNT
     * is the "no clip" sentinel; build_event_id_sentence() refuses it. */
    [VOICE_EV_CONDITIONS_UNSAFE]      = CLIP_COUNT,
    [VOICE_EV_CONDITIONS_SAFE]        = CLIP_ID_conditions_safe,
    [VOICE_EV_GUIDING_STOPPED]        = CLIP_ID_guiding_stopped,
    [VOICE_EV_DOME_SHUTTER_CLOSED]    = CLIP_ID_dome_shutter_closed,
    [VOICE_EV_DOME_SHUTTER_OPENED]    = CLIP_ID_dome_shutter_opened,
    [VOICE_EV_PLATESOLVE_FAILED]      = CLIP_ID_platesolve_failed,
    [VOICE_EV_CAMERA_TIMEOUT]         = CLIP_ID_camera_timeout,
};

/* Events that get the warning tone, mirroring the bad-news category rule in
 * build_event_sentence (categories 1/5/7/8). */
#define VOICE_EV_WARN_MASK                      \
    ((1u << VOICE_EV_SEQUENCE_STEP_FAILED) |    \
     (1u << VOICE_EV_AUTOFOCUS_FAILED)     |    \
     (1u << VOICE_EV_CONDITIONS_UNSAFE)    |    \
     (1u << VOICE_EV_PLATESOLVE_FAILED)    |    \
     (1u << VOICE_EV_CAMERA_TIMEOUT))

/* Assemble a per-event announcement (shared by the live and preview entry
 * points): chime + warning (failure/unsafe events only) + instance + the
 * event's phrase clip.  At most 4 clips, well under SENTENCE_MAX_CLIPS. */
static bool build_event_id_sentence(sentence_t *s, voice_event_t ev,
                                    int instance_idx) {
    /* Single unsigned compare: a negative ev wraps above the count, and the
     * enum's underlying type may be unsigned (so `ev < 0` would be a
     * tautological-compare warning). */
    if ((unsigned)ev >= (unsigned)VOICE_EV_COUNT) return false;
    /* Reserved event with no clip (see s_event_clip).  Guarded here rather
     * than at each caller so the live and preview paths -- and any future one
     * -- all refuse it; the preview endpoint takes the event id straight from
     * an HTTP query, so this IS reachable from outside. */
    if (s_event_clip[ev] >= CLIP_COUNT) return false;
    if (instance_idx < 0 || instance_idx > 2) return false;

    memset(s, 0, sizeof(*s));
    push_clip(s, CLIP_ID_chime);
    if (VOICE_EV_WARN_MASK & (1u << ev)) push_clip(s, CLIP_ID_warning);
    push_clip(s, CLIP_ID_instance_1 + instance_idx);
    push_clip(s, s_event_clip[ev]);
    return true;
}

/* Assemble a grouped equipment announcement: chime + warning (disconnects
 * only, matching build_event_sentence) + instance + each equipment clip for
 * the set bits of eq_mask ascending, with "and" before the last one when two
 * or more are set + connected/disconnected.  A single set bit degenerates to
 * exactly the single-device sentence build_event_sentence produces. */
static bool build_group_sentence(sentence_t *s, int category_bit,
                                 int instance_idx, uint16_t eq_mask) {
    const int n_eq = (int)(sizeof(s_equipment_clip) / sizeof(s_equipment_clip[0]));
    if (category_bit < 0 || category_bit > 1) return false;
    if (instance_idx < 0 || instance_idx > 2) return false;
    eq_mask &= (uint16_t)((1u << n_eq) - 1u);
    if (!eq_mask) return false;

    memset(s, 0, sizeof(*s));
    push_clip(s, CLIP_ID_chime);
    if (category_bit == 1) push_clip(s, CLIP_ID_warning);
    push_clip(s, CLIP_ID_instance_1 + instance_idx);

    int total = 0;
    for (int i = 0; i < n_eq; i++) {
        if (eq_mask & (1u << i)) total++;
    }
    int emitted = 0;
    for (int i = 0; i < n_eq; i++) {
        if (!(eq_mask & (1u << i))) continue;
        if (total >= 2 && emitted == total - 1) push_clip(s, CLIP_ID_and);
        push_clip(s, s_equipment_clip[i]);
        emitted++;
    }
    push_clip(s, (category_bit == 0) ? CLIP_ID_connected : CLIP_ID_disconnected);
    return true;
}

/* Assemble a NINA link announcement (shared by the live and the preview entry
 * points): chime + instance + connected/disconnected.  No warning clip on
 * either edge (user decision). */
static bool build_conn_sentence(sentence_t *s, int instance_idx, bool connected) {
    if (instance_idx < 0 || instance_idx > 2) return false;

    memset(s, 0, sizeof(*s));
    push_clip(s, CLIP_ID_chime);
    push_clip(s, CLIP_ID_instance_1 + instance_idx);
    push_clip(s, connected ? CLIP_ID_connected : CLIP_ID_disconnected);
    return true;
}

/* Per-(slot,instance) 30 s cooldown, shared by the single-event, the grouped
 * equipment and the per-event phrase paths so they pace each other.  Slot is
 * the category bit (0-11) for the category paths and VOICE_EVENT_BIT_BASE + ev
 * for the per-event paths, so a paired event (started/finished) cannot swallow
 * itself.  Deliberately unlocked: callers run on several tasks (WS handlers,
 * esp_timer), but a raced read/write here only risks one duplicate or one
 * suppressed announcement, which is acceptable for a rate limiter. */
static int64_t s_last_event_ms[VOICE_EVENT_BIT_BASE + VOICE_EV_COUNT][3];

static bool event_cooldown_pass(int slot, int instance_idx) {
    int64_t now = esp_timer_get_time() / 1000;
    int64_t last = s_last_event_ms[slot][instance_idx];
    if (last != 0 && now - last < 30000) return false;
    s_last_event_ms[slot][instance_idx] = now;
    return true;
}

/* Post an assembled sentence unconditionally.  Never blocks.  Reserved for
 * the explicit user test/preview entry points (audio_alert_preview_* and
 * audio_alert_test_*); every other caller goes through enqueue() below. */
static void enqueue_always(const sentence_t *s) {
    if (xQueueSend(s_queue, s, 0) != pdTRUE) {
        ESP_LOGW(TAG, "Sentence dropped (queue full)");
    }
}

/* Post an assembled sentence.  Never blocks.  THE global mute gate: every
 * normal sound path in the firmware lands here, so audio_muted silences all
 * of them structurally in one place — no per-call-site checks. */
static void enqueue(const sentence_t *s) {
    if (app_config_get()->audio_muted) return;
    enqueue_always(s);
}

/* ── Playback ───────────────────────────────────────────────────────────── */
static bool codec_open(void) {
    if (s_codec_dead) return false;
    if (!s_codec) {
        s_codec = bsp_audio_codec_speaker_init();
        if (!s_codec) {
            ESP_LOGE(TAG, "Speaker codec init failed; voice alerts disabled");
            s_codec_dead = true;
            return false;
        }
    }

    esp_codec_dev_sample_info_t fs = {
        .bits_per_sample = 16,
        .channel         = 1,
        .channel_mask    = 0,
        .sample_rate     = CLIP_SAMPLE_RATE,
    };
    int rc = esp_codec_dev_open(s_codec, &fs);
    if (rc != ESP_CODEC_DEV_OK) {
        ESP_LOGE(TAG, "Codec open failed: %d", rc);
        return false;
    }

    /* Volume must be set after open (the codec driver rejects it otherwise). */
    int vol = app_config_get()->alert_voice_volume;
    if (vol < 0)   vol = 0;
    if (vol > 100) vol = 100;
    esp_codec_dev_set_out_vol(s_codec, vol);
    return true;
}

static void play_clip(clip_id_t id) {
    /* Acquire-load buf before len (see the ordering comment at clip_override_t). */
    const uint8_t *p = atomic_load_explicit(&s_override[id].buf, memory_order_acquire);
    size_t remain;
    if (p) {
        remain = atomic_load_explicit(&s_override[id].len, memory_order_relaxed);
    } else {
        const clip_t *c = &s_clips[id];
        p = c->start;
        remain = (size_t)(c->end - c->start);
    }

    while (remain) {
        size_t n = (remain < sizeof(s_pcm_buf)) ? remain : sizeof(s_pcm_buf);
        /* Stage through RAM: esp_codec_dev_write() applies software volume in
         * place when the codec has no hardware volume, which would fault on
         * the read-only .rodata clip. */
        memcpy(s_pcm_buf, p, n);
        int rc = esp_codec_dev_write(s_codec, s_pcm_buf, (int)n);
        if (rc != ESP_CODEC_DEV_OK) {
            ESP_LOGW(TAG, "Codec write failed: %d", rc);
            return;
        }
        p += n;
        remain -= n;
    }
}

/**
 * Playback task.  Its stack is deliberately left in internal RAM (plain
 * xTaskCreate) -- the I2S/I2C codec path is not safe to run off a cached PSRAM
 * stack.  Do NOT switch this to a static PSRAM stack.
 */
/* Free retired override buffers.  Runs only on the playback task, between
 * sentences, so no clip can be mid-playback from a buffer being freed. */
static void drain_free_queue(void) {
    void *old;
    while (s_free_q && xQueueReceive(s_free_q, &old, 0) == pdTRUE) {
        heap_caps_free(old);
    }
}

static void audio_alert_task(void *arg) {
    (void)arg;
    sentence_t s;

    for (;;) {
        if (xQueueReceive(s_queue, &s, portMAX_DELAY) != pdTRUE) continue;
        drain_free_queue();

        if (!codec_open()) {
            xQueueReset(s_queue);   /* speaker is unusable; don't pile up */
            continue;
        }

        do {
            for (int i = 0; i < s.count; i++) {
                play_clip((clip_id_t)s.clip[i]);
            }
        } while (xQueueReceive(s_queue, &s, pdMS_TO_TICKS(DRAIN_WAIT_MS)) == pdTRUE);

        esp_codec_dev_close(s_codec);   /* PA standby: no idle hiss */
        drain_free_queue();
    }
}

/* ── Public API ─────────────────────────────────────────────────────────── */

void audio_alert_init(void) {
    if (s_queue) return;

    s_queue = xQueueCreate(SENTENCE_QUEUE_LEN, sizeof(sentence_t));
    if (!s_queue) {
        ESP_LOGE(TAG, "Queue alloc failed");
        return;
    }

    /* One retire slot per clip: enough for a replace-all while idle. */
    s_free_q = xQueueCreate(CLIP_COUNT, sizeof(void *));
    if (!s_free_q) {
        /* Playback still works, but replaced override buffers will be leaked
         * (set_override must never free inline while the task is live). */
        ESP_LOGE(TAG, "Free-queue alloc failed; replaced clip buffers will leak");
    }

    if (xTaskCreate(audio_alert_task, "audio_alert", 4096, NULL, 3, NULL) != pdPASS) {
        ESP_LOGE(TAG, "Task create failed");
        vQueueDelete(s_queue);
        s_queue = NULL;
        if (s_free_q) {
            vQueueDelete(s_free_q);
            s_free_q = NULL;
        }
        return;
    }

    ESP_LOGI(TAG, "Audio alerts initialized");
}

int audio_alert_clip_count(void) {
    return CLIP_COUNT;
}

const char *audio_alert_clip_name(int idx) {
    return (idx >= 0 && idx < CLIP_COUNT) ? s_clip_names[idx] : NULL;
}

void audio_alert_set_override(int idx, const uint8_t *pcm, size_t len) {
    if (idx < 0 || idx >= CLIP_COUNT) return;

    /* Writer is serialized (voice_store mutex), so a relaxed load is fine. */
    const uint8_t *old = atomic_load_explicit(&s_override[idx].buf, memory_order_relaxed);
    if (pcm) {
        /* Apply: len (relaxed) before buf (release) — see clip_override_t. */
        atomic_store_explicit(&s_override[idx].len, len, memory_order_relaxed);
        atomic_store_explicit(&s_override[idx].buf, pcm, memory_order_release);
    } else {
        /* Clear: buf (NULL) before len. */
        atomic_store_explicit(&s_override[idx].buf, NULL, memory_order_relaxed);
        atomic_store_explicit(&s_override[idx].len, 0, memory_order_relaxed);
    }

    if (!old) return;
    if (!s_queue) {
        /* No playback task exists (s_queue is only non-NULL once the task is
         * running), so nothing can be mid-playback: freeing inline is safe. */
        heap_caps_free((void *)old);
        return;
    }
    if (!s_free_q || xQueueSend(s_free_q, &old, 0) != pdTRUE) {
        /* Retire queue missing (alloc failed at init) or full (many
         * replacements with no playback in between).  Leaking beats freeing a
         * buffer the playback task might still be streaming. */
        ESP_LOGW(TAG, "Override retire unavailable; leaking old clip buffer");
    }
}

void audio_alert_speak(alert_type_t type, int instance_idx, float value) {
    if (!s_queue) return;
    app_config_t *cfg = app_config_get();
    if (!cfg->alert_voice_enabled) return;
    /* Per-instance mute — live path only; the test endpoints bypass it so the
     * speaker stays testable while an instance is muted. */
    if (instance_idx >= 0 && instance_idx < 3 && cfg->alert_voice_muted[instance_idx]) return;

    sentence_t s;
    if (build_sentence(&s, type, instance_idx, value)) enqueue(&s);
}

void audio_alert_speak_event(int category_bit, int instance_idx, int equipment_idx) {
    if (!s_queue) return;
    if (category_bit < 0 || category_bit > 11) return;
    if (instance_idx < 0 || instance_idx > 2) return;

    app_config_t *cfg = app_config_get();
    if (!cfg->alert_voice_enabled) return;
    if (cfg->alert_voice_muted[instance_idx]) return;
    if (!(cfg->voice_notify_mask & (1u << category_bit))) return;
    if (!event_cooldown_pass(category_bit, instance_idx)) return;

    sentence_t s;
    if (build_event_sentence(&s, category_bit, instance_idx, equipment_idx)) enqueue(&s);
}

void audio_alert_speak_equipment_group(int category_bit, int instance_idx,
                                       uint16_t eq_mask) {
    if (!s_queue) return;
    if (category_bit < 0 || category_bit > 1) return;
    if (instance_idx < 0 || instance_idx > 2) return;
    if (!eq_mask) return;

    app_config_t *cfg = app_config_get();
    if (!cfg->alert_voice_enabled) return;
    if (cfg->alert_voice_muted[instance_idx]) return;
    if (!(cfg->voice_notify_mask & (1u << category_bit))) return;
    if (!event_cooldown_pass(category_bit, instance_idx)) return;

    sentence_t s;
    if (build_group_sentence(&s, category_bit, instance_idx, eq_mask)) enqueue(&s);
}

void audio_alert_speak_event_id(voice_event_t ev, int instance_idx) {
    if (!s_queue) return;
    if ((unsigned)ev >= (unsigned)VOICE_EV_COUNT) return;
    if (instance_idx < 0 || instance_idx > 2) return;

    app_config_t *cfg = app_config_get();
    if (!cfg->alert_voice_enabled) return;
    if (cfg->alert_voice_muted[instance_idx]) return;
    /* The per-event bit is checked ALONE, deliberately NOT ANDed with the
     * event's category bit: ticking "Sequence finished" must be enough to hear
     * it.  The category bits keep governing only the generic fallback clips. */
    if (!(cfg->voice_notify_mask & (1u << (VOICE_EVENT_BIT_BASE + (int)ev)))) return;
    if (!event_cooldown_pass(VOICE_EVENT_BIT_BASE + (int)ev, instance_idx)) return;

    sentence_t s;
    if (build_event_id_sentence(&s, ev, instance_idx)) enqueue(&s);
}

void audio_alert_preview_event_id(voice_event_t ev, int instance_idx) {
    if (!s_queue) return;

    sentence_t s;
    if (build_event_id_sentence(&s, ev, instance_idx)) enqueue_always(&s);
}

const char *audio_alert_event_clip_name(voice_event_t ev) {
    if ((unsigned)ev >= (unsigned)VOICE_EV_COUNT) return NULL;
    if (s_event_clip[ev] >= CLIP_COUNT) return NULL;   /* reserved, no clip */
    return s_clip_names[s_event_clip[ev]];
}

void audio_alert_speak_conn(int instance_idx, bool connected) {
    if (!s_queue) return;
    if (instance_idx < 0 || instance_idx > 2) return;

    app_config_t *cfg = app_config_get();
    if (!cfg->alert_voice_enabled) return;
    if (cfg->alert_voice_muted[instance_idx]) return;
    if (!(connected ? cfg->alert_voice_conn : cfg->alert_voice_disc)) return;

    sentence_t s;
    if (build_conn_sentence(&s, instance_idx, connected)) enqueue(&s);
}

void audio_alert_preview_conn(int instance_idx, bool connected) {
    if (!s_queue) return;

    sentence_t s;
    if (build_conn_sentence(&s, instance_idx, connected)) enqueue_always(&s);
}

void audio_alert_play_boot_jingle(void) {
    if (!s_queue) return;
    if (!app_config_get()->boot_jingle_enabled) return;

    sentence_t s = { .clip = { (uint8_t)CLIP_ID_boot_jingle }, .count = 1 };
    enqueue(&s);
}

void audio_alert_preview_jingle(void) {
    if (!s_queue) return;

    sentence_t s = { .clip = { (uint8_t)CLIP_ID_boot_jingle }, .count = 1 };
    enqueue_always(&s);
}

void audio_alert_preview_event(int category_bit, int instance_idx, int equipment_idx) {
    if (!s_queue) return;

    sentence_t s;
    if (build_event_sentence(&s, category_bit, instance_idx, equipment_idx)) enqueue_always(&s);
}

void audio_alert_test_speak(alert_type_t type, int instance_idx, float value) {
    if (!s_queue) return;

    sentence_t s;
    if (build_sentence(&s, type, instance_idx, value)) enqueue_always(&s);
}

bool audio_alert_test_clip(const char *name) {
    if (!s_queue || !name) return false;

    for (int i = 0; i < CLIP_COUNT; i++) {
        if (strcmp(name, s_clip_names[i]) != 0) continue;
        sentence_t s = { .clip = { (uint8_t)i }, .count = 1 };
        enqueue_always(&s);
        return true;
    }
    return false;
}
