/**
 * @file audio_alert.c
 * @brief Spoken alert playback over the onboard ES8311 speaker (thread-safe).
 *
 * Architecture: audio_alert_speak() turns (type, instance, value) into a list
 * of clip ids and posts it to a queue.  The audio_alert task drains the queue,
 * lazily brings up the speaker codec on first use, plays each sentence clip by
 * clip and closes the codec once the queue stays empty for DRAIN_WAIT_MS
 * (closing puts the power amp in standby, which kills the idle hiss).
 *
 * Clips are headerless 16 kHz / 16-bit / mono PCM embedded via EMBED_FILES in
 * main/CMakeLists.txt.  Placeholders are generated by
 * tools/gen_placeholder_clips.py; dropping real renders in main/audio_clips/
 * needs no code change.
 */

#include "audio_alert.h"
#include "app_config.h"
#include "bsp/esp-bsp.h"        /* bsp_audio_codec_speaker_init */
#include "esp_codec_dev.h"
#include "esp_log.h"
#include "freertos/FreeRTOS.h"
#include "freertos/queue.h"
#include "freertos/task.h"
#include <string.h>

static const char *TAG = "audio_alert";

#define CLIP_SAMPLE_RATE    16000
#define SENTENCE_MAX_CLIPS  12      /* chime+warning+instance+metric+"999.9"+limit = 9 */
#define SENTENCE_QUEUE_LEN  8   /* match the 8-deep flash queue in nina_alerts.c */
#define PCM_CHUNK_BYTES     2048
#define DRAIN_WAIT_MS       400     /* keep the PA up this long between sentences */
#define VALUE_MAX_TENTHS    9999    /* clamp: nothing above "999.9" is spoken */

/* ── Embedded clip registry ─────────────────────────────────────────────────
 * One list drives the extern declarations, the id enum, the address table and
 * the name table, so they cannot drift out of order.  EMBED_FILES derives the
 * symbol from the file's basename only, so the audio_clips/ subdirectory does
 * not appear in the symbol name.  Each X() argument is both the .pcm basename
 * and the name the /api/test/clip endpoint accepts. */
#define CLIP_LIST(X)                                            \
    X(chime) X(warning)                                         \
    X(instance_1) X(instance_2) X(instance_3)                   \
    X(rms) X(hfr) X(above_limit) X(unsafe) X(point)             \
    X(digit_0) X(digit_1) X(digit_2) X(digit_3) X(digit_4)      \
    X(digit_5) X(digit_6) X(digit_7) X(digit_8) X(digit_9)

#define CLIP_EXTERN(name)                               \
    extern const uint8_t _binary_##name##_pcm_start[];  \
    extern const uint8_t _binary_##name##_pcm_end[];
#define CLIP_ENUM(name)  CLIP_ID_##name,
#define CLIP_ENTRY(name) { _binary_##name##_pcm_start, _binary_##name##_pcm_end },
#define CLIP_NAME(name)  #name,

CLIP_LIST(CLIP_EXTERN)

/* CLIP_ID_instance_1 and CLIP_ID_digit_0 are indexed with an offset. */
typedef enum {
    CLIP_LIST(CLIP_ENUM)
    CLIP_COUNT
} clip_id_t;

typedef struct {
    const uint8_t *start;
    const uint8_t *end;
} clip_t;

static const clip_t      s_clips[CLIP_COUNT]      = { CLIP_LIST(CLIP_ENTRY) };
static const char *const s_clip_names[CLIP_COUNT] = { CLIP_LIST(CLIP_NAME) };

/* ── Module state ───────────────────────────────────────────────────────── */
typedef struct {
    uint8_t clip[SENTENCE_MAX_CLIPS];
    uint8_t count;
} sentence_t;

static QueueHandle_t          s_queue = NULL;
static esp_codec_dev_handle_t s_codec = NULL;   /* task-owned, lazily created */
static bool                   s_codec_dead = false;   /* init failed once: never retry
                                                       * (BSP leaves dangling I2S handles
                                                       * that assert on a second attempt) */
static uint8_t                s_pcm_buf[PCM_CHUNK_BYTES];

/* ── Sentence assembly ──────────────────────────────────────────────────── */
static void push_clip(sentence_t *s, clip_id_t id) {
    if (s->count < SENTENCE_MAX_CLIPS) {
        s->clip[s->count++] = (uint8_t)id;
    }
}

/* Speak `value` as "<digits> point <digit>", e.g. 1.25 -> "one point three".
 * Integer math throughout: no float formatting on the caller's stack. */
static void push_value(sentence_t *s, float value) {
    int tenths = (value > 0.0f) ? (int)(value * 10.0f + 0.5f) : 0;
    if (tenths > VALUE_MAX_TENTHS) tenths = VALUE_MAX_TENTHS;

    int whole = tenths / 10;
    if (whole >= 100) push_clip(s, CLIP_ID_digit_0 + (whole / 100) % 10);
    if (whole >= 10)  push_clip(s, CLIP_ID_digit_0 + (whole / 10) % 10);
    push_clip(s, CLIP_ID_digit_0 + whole % 10);
    push_clip(s, CLIP_ID_point);
    push_clip(s, CLIP_ID_digit_0 + tenths % 10);
}

/* Assemble the announcement.  Shared by the live and the test entry points --
 * the only difference between them is the alert_voice_enabled gate.
 * Returns false for arguments that have nothing sensible to say. */
static bool build_sentence(sentence_t *s, alert_type_t type, int instance_idx,
                           float value) {
    if (instance_idx < 0 || instance_idx > 2) return false;

    memset(s, 0, sizeof(*s));
    push_clip(s, CLIP_ID_chime);
    push_clip(s, CLIP_ID_warning);
    push_clip(s, CLIP_ID_instance_1 + instance_idx);

    switch (type) {
    case ALERT_RMS:
    case ALERT_HFR:
        push_clip(s, (type == ALERT_RMS) ? CLIP_ID_rms : CLIP_ID_hfr);
        push_value(s, value);
        push_clip(s, CLIP_ID_above_limit);
        return true;
    case ALERT_SAFETY:
        push_clip(s, CLIP_ID_unsafe);
        return true;
    default:
        return false;   /* unknown type: nothing sensible to say */
    }
}

/* Post an assembled sentence.  Never blocks. */
static void enqueue(const sentence_t *s) {
    if (xQueueSend(s_queue, s, 0) != pdTRUE) {
        ESP_LOGW(TAG, "Sentence dropped (queue full)");
    }
}

/* ── Playback ───────────────────────────────────────────────────────────── */
static bool codec_open(void) {
    if (s_codec_dead) return false;
    if (!s_codec) {
        s_codec = bsp_audio_codec_speaker_init();
        if (!s_codec) {
            ESP_LOGE(TAG, "Speaker codec init failed; voice alerts disabled");
            s_codec_dead = true;
            return false;
        }
    }

    esp_codec_dev_sample_info_t fs = {
        .bits_per_sample = 16,
        .channel         = 1,
        .channel_mask    = 0,
        .sample_rate     = CLIP_SAMPLE_RATE,
    };
    int rc = esp_codec_dev_open(s_codec, &fs);
    if (rc != ESP_CODEC_DEV_OK) {
        ESP_LOGE(TAG, "Codec open failed: %d", rc);
        return false;
    }

    /* Volume must be set after open (the codec driver rejects it otherwise). */
    int vol = app_config_get()->alert_voice_volume;
    if (vol < 0)   vol = 0;
    if (vol > 100) vol = 100;
    esp_codec_dev_set_out_vol(s_codec, vol);
    return true;
}

static void play_clip(clip_id_t id) {
    const clip_t *c = &s_clips[id];
    const uint8_t *p = c->start;
    size_t remain = (size_t)(c->end - c->start);

    while (remain) {
        size_t n = (remain < sizeof(s_pcm_buf)) ? remain : sizeof(s_pcm_buf);
        /* Stage through RAM: esp_codec_dev_write() applies software volume in
         * place when the codec has no hardware volume, which would fault on
         * the read-only .rodata clip. */
        memcpy(s_pcm_buf, p, n);
        int rc = esp_codec_dev_write(s_codec, s_pcm_buf, (int)n);
        if (rc != ESP_CODEC_DEV_OK) {
            ESP_LOGW(TAG, "Codec write failed: %d", rc);
            return;
        }
        p += n;
        remain -= n;
    }
}

/**
 * Playback task.  Its stack is deliberately left in internal RAM (plain
 * xTaskCreate) -- the I2S/I2C codec path is not safe to run off a cached PSRAM
 * stack.  Do NOT switch this to a static PSRAM stack.
 */
static void audio_alert_task(void *arg) {
    (void)arg;
    sentence_t s;

    for (;;) {
        if (xQueueReceive(s_queue, &s, portMAX_DELAY) != pdTRUE) continue;

        if (!codec_open()) {
            xQueueReset(s_queue);   /* speaker is unusable; don't pile up */
            continue;
        }

        do {
            for (int i = 0; i < s.count; i++) {
                play_clip((clip_id_t)s.clip[i]);
            }
        } while (xQueueReceive(s_queue, &s, pdMS_TO_TICKS(DRAIN_WAIT_MS)) == pdTRUE);

        esp_codec_dev_close(s_codec);   /* PA standby: no idle hiss */
    }
}

/* ── Public API ─────────────────────────────────────────────────────────── */

void audio_alert_init(void) {
    if (s_queue) return;

    s_queue = xQueueCreate(SENTENCE_QUEUE_LEN, sizeof(sentence_t));
    if (!s_queue) {
        ESP_LOGE(TAG, "Queue alloc failed");
        return;
    }

    if (xTaskCreate(audio_alert_task, "audio_alert", 4096, NULL, 3, NULL) != pdPASS) {
        ESP_LOGE(TAG, "Task create failed");
        vQueueDelete(s_queue);
        s_queue = NULL;
        return;
    }

    ESP_LOGI(TAG, "Audio alerts initialized");
}

void audio_alert_speak(alert_type_t type, int instance_idx, float value) {
    if (!s_queue) return;
    if (!app_config_get()->alert_voice_enabled) return;

    sentence_t s;
    if (build_sentence(&s, type, instance_idx, value)) enqueue(&s);
}

void audio_alert_test_speak(alert_type_t type, int instance_idx, float value) {
    if (!s_queue) return;

    sentence_t s;
    if (build_sentence(&s, type, instance_idx, value)) enqueue(&s);
}

bool audio_alert_test_clip(const char *name) {
    if (!s_queue || !name) return false;

    for (int i = 0; i < CLIP_COUNT; i++) {
        if (strcmp(name, s_clip_names[i]) != 0) continue;
        sentence_t s = { .clip = { (uint8_t)i }, .count = 1 };
        enqueue(&s);
        return true;
    }
    return false;
}
