#pragma once

#include <stdbool.h>
#include "esp_err.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    SPOTIFY_AUTH_NONE,
    SPOTIFY_AUTH_AUTHORIZED,
    SPOTIFY_AUTH_ERROR
} spotify_auth_state_t;

/**
 * Initialize Spotify auth — loads tokens from NVS if present.
 */
void spotify_auth_init(void);

/**
 * Get current auth state.
 */
spotify_auth_state_t spotify_auth_get_state(void);

/**
 * Exchange authorization code for tokens (PKCE flow).
 * Called by web handler when /api/spotify/callback is hit.
 * @param code           Authorization code from Spotify redirect
 * @param code_verifier  PKCE code verifier (generated by browser JS)
 * @param redirect_uri   The redirect URI used in the auth request
 * @return ESP_OK on success
 */
esp_err_t spotify_auth_exchange_code(const char *code, const char *code_verifier,
                                      const char *redirect_uri);

/**
 * Get a valid access token (refreshes if expired).
 * Copies the token into a caller-provided buffer for thread safety.
 * @param buf      Destination buffer
 * @param buf_size Size of destination buffer (recommend 1024)
 * @return ESP_OK on success (token copied), ESP_FAIL if not authorized / refresh failed
 */
esp_err_t spotify_auth_get_access_token(char *buf, size_t buf_size);

/**
 * Clear all stored tokens (logout).
 */
void spotify_auth_logout(void);

/**
 * Invalidate the cached access token, forcing a refresh on next use.
 * Call this when a Spotify API request returns HTTP 401.
 */
void spotify_auth_invalidate_token(void);

/**
 * Check if tokens are stored (may still be expired/invalid).
 */
bool spotify_auth_has_tokens(void);

#ifdef __cplusplus
}
#endif
